// Generated by CoffeeScript 1.7.1
(function() {
  var courseTopc;

  courseTopc = 'coffeescript';

  console.log(courseTopic);

  console.log(this.courseTopic);

  console.log(window.courseTopic);

}).call(this);
